### PR TITLE
Update usage.md with recurring-donations instructions

### PR DESCRIPTION
**Pull request by nixbitcoin**

### CODE REVIEW

**Comment by nixbitcoin** [comment]
https://github.com/jonasnick/nix-bitcoin/issues/35

**Comment by jonasnick** [comment]
I think ideally a new entry in usage.md wouldn't be needed. What do you think about moving item 2. and 4. to configuration.nix?

**Comment by nixbitcoin** [comment]
Implemented in 4364e7c. I agree for at least as long as recurring-donations is experimental. What is your long-term vision for `docs/usage.md`?

**Comment by jonasnick** [comment]
looks good to me. `docs/usage.md` should only contain explanations for things which have no place in configuration.nix.

**Pull request merged**
